version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  parser_worker:
    build: ./app/
    env_file:
      - app/.env
    volumes:
      - ./app:/app
    command: python services/rabbit/workers/parser.py
    depends_on:
      rabbitmq:
        condition: service_started
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 2

